[~time~] Нас покинула ~who~ из ~location~
[~time~] ~who~ из ~location~ уже не с нами.
[~time~] ~who~ из ~location~ раскланялась и ушла
[~time~] От нас ушла ~who~ из ~location~
[~time~] Ушлa ~who~ из ~location~
[~time~] Беззвучно исчезла ~who~ из ~location~
[~time~] Раскланялась и исчезла ~who~ из ~location~
[~time~] ~who~ из ~location~ прощается со всеми и уходит
[~time~] Свалила ~who~ из ~location~