[~time~] Нас покинуло ~who~ из ~location~
[~time~] ~who~ из ~location~ уже не с нами
[~time~] ~who~ из ~location~ раскланялось и ушло
[~time~] От нас ушло ~who~ из ~location~
[~time~] Ушло ~who~ из ~location~
[~time~] Беззвучно исчезло ~who~ из ~location~
[~time~] Раскланялось и исчезло ~who~ из ~location~
[~time~] ~who~ из ~location~ прощается со всеми и уходит
[~time~] Свалило ~who~ из ~location~