[~time~] Нас покинул ~who~ из ~location~
[~time~] ~who~ из ~location~ уже не с нами
[~time~] ~who~ из ~location~ раскланялся и ушел
[~time~] От нас ушел ~who~ из ~location~
[~time~] Ушел ~who~ из ~location~
[~time~] Беззвучно исчез ~who~ из ~location~
[~time~] Раскланялся и исчез ~who~ из ~location~
[~time~] ~who~ из ~location~ прощается со всеми и уходит
[~time~] Свалил ~who~ из ~location~