[~time~] К нам присоединилась ~who~ из ~location~
[~time~] Нас посетила ~who~ из ~location~
[~time~] К нам присоединилась ~who~ из ~location~, поприветствуем
[~time~] К нам присоединяется ~who~ из ~location~
[~time~] К нам прибыла ~who~ из ~location~
[~time~] К нам пришла ~who~ из ~location~
[~time~] К нам в чат на огонёк зашла ~who~ из ~location~
[~time~] Совершенно неожиданно появилась ~who~ из ~location~
[~time~] Разрешите представить: ~who~ из ~location~
[~time~] ~who~ из ~location~ подключилась к чату
[~time~] ~who~ из ~location~ снова с нами! Дружно скажем "здрасти"!
[~time~] Вдруг откуда ни возьмись появилась ~who~ из ~location~