#ifndef RTYPES_CLAN____H
#define RTYPES_CLAN____H




enum CLAN_MSG
{
    __TYPE_SEND_CHAT_EVENT		=2,
    __TYPE_SET_DATA			=3,
    __TYPE_LOGIN_NOTIFY_LOGGED_IN	=4,
    __TYPE_REGISTER_ALL_NICKS		=5,
    __TYPE_NOTIFY_USER_LOGGED_OUT	=7,
    __TYPE_NOTIFY_USER_LOGGED_IN	=8,
    __TYPE_SEND_HTTP_REQUEST		=9,
    __TYPE_SEND_CHAT_DATA		=10,
    __TYPE_UNREGISTER_ALL_NICKS		=11,
    __TYPE_UNREGISTER_1_NICKS		=12,
    __TYPE_START_SERVICE		=13,
    __TYPE_SEND_CHAT_DATA_TO_CS_ONLY	=15,
    __TYPE_SEND_STUFF_DATA		=16
};
#endif
