[~time~] К нам присоединился ~who~ из ~location~
[~time~] Нас посетил ~who~ из ~location~
[~time~] К нам присоединился ~who~ из ~location~, поприветствуем
[~time~] К нам присоединяется ~who~ из ~location~
[~time~] К нам прибыл ~who~ из ~location~
[~time~] К нам пришел ~who~ из ~location~
[~time~] К нам в чат на огонёк зашёл ~who~ из ~location~
[~time~] Совершенно неожиданно появился ~who~ из ~location~
[~time~] Разрешите представить: ~who~ из ~location~
[~time~] ~who~ из ~location~ подключился к чату
[~time~] ~who~ из ~location~ снова с нами! Дружно скажем "здрасти"!
[~time~] Вдруг откуда ни возьмись появился ~who~ из ~location~