[~time~] К нам присоединилось ~who~ из ~location~
[~time~] Нас посетило ~who~ из ~location~
[~time~] К нам присоединилось ~who~ из ~location~, поприветствуем
[~time~] К нам присоединяется ~who~ из ~location~
[~time~] К нам прибыло ~who~ из ~location~
[~time~] К нам пришло ~who~ из ~location~
[~time~] К нам в чат на огонёк зашло ~who~ из ~location~
[~time~] Совершенно неожиданно появилось ~who~ из ~location~
[~time~] Разрешите представить: ~who~ из ~location~
[~time~] ~who~ из ~location~ подключилось к чату
[~time~] ~who~ из ~location~ снова с нами! Дружно скажем "здрасти"!
[~time~] Вдруг откуда ни возьмись появилось ~who~ из ~location~