alter table users add column  `icq` text;
alter table users add column   `city` text;
alter table users add column   `info` text;
alter table users add column   `homepage` text;
alter table users add column   `tel` text;
alter table users add column   `b_day` varchar(10) NOT NULL default '';
alter table users add column   `b_mon` int(3) NOT NULL default '0';
alter table users add column   `b_year` varchar(4) NOT NULL default '1980';
alter table users add column   `fname` text;
alter table users add column   `lname` text;
alter table users add column   `email` text;
alter table users add column   `reg_date` datetime default NULL;
alter table users add column   `login` varchar(18) NOT NULL default '';
alter table users add column   `pass` text;
alter table users add column   `upperlogin` varchar(20) NOT NULL default '';
alter table users add column   `gender` char(1) NOT NULL default '0';
alter table users add column   `hide_fname` char(1) NOT NULL default '0';
alter table users add column   `hide_lname` char(1) NOT NULL default '0';
alter table users add column   `hide_bdate` char(1) NOT NULL default '0';
alter table users add column   `hide_tel` char(1) NOT NULL default '0';
alter table users add column   `hide_icq` char(1) NOT NULL default '0';
alter table users add column   `hide_email` char(1) NOT NULL default '0';
alter table users add column   `bought_invisibility` double NOT NULL default '0';
alter table users add column   `bought_quota` int(10) NOT NULL default '0';
alter table users add column   `family_status` text NOT NULL;
alter table users add column   `hide_family_status` char(1) NOT NULL default '0';
alter table users add   KEY (`login`);
alter table users add   KEY (`reg_date`);
