alter table users add column  `setting_lpp` int(3) NOT NULL default '100';
alter table users add column  `setting_show_nicks` char(1) NOT NULL default '1';
alter table users add column    `setting_show_level` char(1) NOT NULL default '1';
alter table users add column    `setting_neye` int(3) NOT NULL default '0';
alter table users add column    `setting_n_color_pack` int(4) NOT NULL default '0';

alter table users add column    `contact_mode` char(1) NOT NULL default '0';
alter table users add column    `contact_options` int(10) unsigned NOT NULL default '0';
alter table users add column    `notes_msg_per_page` int(11) NOT NULL default '20';
alter table users add column    `notes_save_copy` char(1) NOT NULL default '0';
alter table users add column    `notes_sort` char(1) NOT NULL default '1';
alter table users add column    `notes_sort_desc` char(1) NOT NULL default '1';
alter table users add column    `poweshen` int(11) NOT NULL default '0';
alter table users add column    `last_nick_id` int(11) NOT NULL default '0';
alter table users add column    `last_nick` text NOT NULL;
alter table users add column    `last_channel` int(11) NOT NULL default '0';
alter table users add column    `last_status_id` int(11) NOT NULL default '0';
alter table users add column    `setting_autologin` char(1) NOT NULL default '0';
alter table users add column    `setting_autochange` char(1) NOT NULL default '0';
alter table users add column    `setting_show_eye` char(1) NOT NULL default '0';
alter table users add column    `setting_show_hints` char(1) NOT NULL default '0';
alter table users add column    `setting_show_stat` char(1) NOT NULL default '0';
alter table users add column    `setting_invite_sound` char(1) NOT NULL default '0';
alter table users add column    `setting_full_buttons` char(1) NOT NULL default '0';
alter table users add column    `ul_mode_hide_female` char(1) NOT NULL default '0';
alter table users add column    `ul_mode_hide_male` char(1) NOT NULL default '0';
alter table users add column    `ul_mode_contacts_only` char(1) NOT NULL default '0';
alter table users add column    `setting_show_credits` char(1) NOT NULL default '0';
alter table users add column    `primary_photo` int(10) unsigned NOT NULL default '0';
alter table users add column    `level` int(10) unsigned NOT NULL default '100';
alter table users add column    `vote_balls` int(10) unsigned NOT NULL default '0';
alter table users add column    `db_privileges` int(10) NOT NULL default '0';
alter table users add column    `last_www_channel` text NOT NULL;
alter table users add column    `unread_notes` int(11) NOT NULL default '0';
